### PR TITLE
fix executable and windows build

### LINKED ISSUE #187: Test distributable packages
Either automated test that it runs, stops and checks exit code or at least include manual test of the distributables in the documented steps to create a new release.

### PR DESCRIPTION
**Pull request by rerpha**
### Issue

Closes #187 

### Description of work

Unpinning cx_freeze - the issue on windows has been fixed in 6.0
https://github.com/anthony-tuininga/cx_Freeze/issues/407

Also fixing the executable (had been broken for a while) and developing a test to make sure it doesn't break again. 

code changes mean that the definitions dir only has to be found once rather than all over the code.

### Acceptance Criteria 

N/A

### UI tests

N/A

### Nominate for Group Code Review

- [ ] Nominate for code review

### CODE REVIEW

**Comment by matthew-d-jones** [comment]
Waiting until we have Windows and Mac Jenkins nodes up before reviewing this PR.

**Comment by rerpha** [comment]
now seems to work.

**Comment by rerpha** [comment]
TODO: add a simple status-code dependent test of the executable 
TODO: try and slim the executable down a bit

**Comment by rerpha** [comment]
still need to get the test working

**Comment by rerpha** [comment]
will need to log into the build node and uninstall cx-freeze in order for this to work.

**Comment by rerpha** [comment]
executable is working so it's just the test that needs properly implementing.

**Pull request merged**
