### PR TITLE
ECDC-2435: Enable live update of transformations

### PR DESCRIPTION
**Pull request by umithardal**
### Issue

ECDC-2435

### Description of work
This PR enables live update of value changes in transformations view. In addition some code clear up and enhancement has been done.

Easiest way to see if changes work:

- Change the `value` field next to `Scalar dataset` (under `Distance` if it is a `Translation`, or under `Angle` if it is a `Rotation`. `Vale to use in 3D view` should change simultaneously. Before the changes in this PR, you have to a an `Enter` to update `3D view` value.

### CODE REVIEW

**Comment by zjttoefs** [comment]
I can see the "Value to use in 3D" change in sync. But the 3D view does not update anymore.

**Review by zjttoefs — CHANGES_REQUESTED** [review]
The 3D view needs to update, obviously. Maybe some of the deleted emits were needed.

There are some previously static methods appear no longer to be static and some comments on those changes would be good to see. In general I would prefer the separate the renaming and reordering from the functional changes into different PRs.

**Comment by umithardal** [comment]
> The 3D view needs to update, obviously. Maybe some of the deleted emits were needed.
> 
> There are some previously static methods appear no longer to be static and some comments on those changes would be good to see. In general I would prefer the separate the renaming and reordering from the functional changes into different PRs.

Now, the description of the problem unfortunately misses the detail. It states that once user changes the focus, the new values takes place. However, until you press `Enter` nothing changes in the 3D view.

With the latest commit I re-added the `emit` signals. You can now see the 3D view updates simultaneously with changes without the need of changing focus or pressing any key. The trade off is we have to emit each time there is change in one of the relevant fields.  I miss calculated the signal-slot behaviour of PYQT, and thus wrongfully removed emits. Thanks for the review and catch.

On the other side of the coin; I had a really hard time understanding the code, and could not solve the problem. So, what I did is to implement a proper `__init__` constructor so that attribute definitions are in proper place. I then refactored to make things readable. With these changes, we only need to create an instance of the object, rather than creating it and calling a method of it.

Only thing that I changed which can be considered as rather a fix is the removal of the inheritance of builtin Python `Object` from the definition of the class. Which was a requirement in Python 2 but as of Python 3 it is not.

Other changes in names basically follows PEP.

**Comment by mattclarke** [comment]
To reinforce what Tobias said.
As a group, we are all guilty of combining refactoring/reformatting with behaviour changes - this needs to stop.
It can make it hard for the reviewer to work out what has changed.
If we do the refactoring/reformatting in a separate PR then it can be reviewed in 30 seconds.
I'll bring this up in the meeting today.

**Comment by mattclarke** [comment]
> Now, the description of the problem unfortunately misses the detail. It states that once user changes the focus, the new values takes place. However, until you press Enter nothing changes in the 3D view.

The description is a starting point. Unfortunately it is unlikely to contain all the information you need to solve the problem especially when it was written by someone intimate with the code base.
This is your cue to explore the details and make sure you understand the problem before getting started.

**Comment by mattclarke** [comment]
> I can see the "Value to use in 3D" change in sync. But the 3D view does not update anymore.

These things happen to all of us from time to time, so don't beat yourself up about it, but take it as a reminder to make sure you test things sufficiently before it gets to review.

**Comment by mattclarke** [comment]
I propose we close this PR and resubmit it as two PRs, one reformatting/refactoring and then one with the functional change.

**Pull request closed without merging**
