### PR TITLE
322: edit component window

### LINKED ISSUE #322: Widgets: edit component window
Add an "edit component" window much like the add component window - this should be able to use the UI file for the add component window. 

This relies on the list view being completed for the button to exist on a component view.

### PR DESCRIPTION
**Pull request by rerpha**
### Issue

Closes #322 

### Description of work

Adds an edit component button and associated window to components. 
in progress - still need to do fields

### Acceptance Criteria 

- Add a component, edit it, click edit, check no changes have been made 
- change shape types and check the changes are reflected in the 3d view 

### UI tests

Added some UI tests for the add/edit component window

### Nominate for Group Code Review

- [ ] Nominate for code review

### CODE REVIEW

**Comment by rerpha** [comment]
I'm not sure whether i should be putting fields in here as they are not yet fully implemented anyway?

**Comment by rerpha** [comment]
> Currently breaks adding new components with fields.

would you mind posting the steps you took to break it? i tried earlier but couldn't seem to break it in the add or edit component window, but was only trying with a couple of fields

**Comment by matthew-d-jones** [comment]
@rerpha 
- Start a new NeXus-Constructor
- Add component
- Add field
- Create a scalar string dataset with any name and string value
- Add Component

I get:
```
Traceback (most recent call last):
  File "/home/jonmd/git/nexus-constructor/nexus_constructor/add_component_window.py", line 306, in on_ok
    add_fields_to_component(component, self.fieldsListWidget)
  File "/home/jonmd/git/nexus-constructor/nexus_constructor/component_fields.py", line 234, in add_fields_to_component
    component.set_field(widget.name, widget.value, widget.dtype)
  File "/home/jonmd/git/nexus-constructor/nexus_constructor/component_fields.py", line 170, in value
    self.value_line_edit.text()
TypeError: 'numpy.dtype' object is not callable
```

**Comment by matthew-d-jones** [comment]
@rerpha oh, just realised it is broken in the same way on `switch_to_widgets` branch :(

**Pull request merged**
