### PR TITLE
722 Show Button labels in ToolBar

### PR DESCRIPTION
**Pull request by ebadkamil**
Try to address the issue https://github.com/ess-dmsc/nexus-constructor/issues/722 .

### CODE REVIEW

**Comment by ebadkamil** [comment]
Most likely we will need better way to put labels and actions together.

**Comment by mattclarke** [comment]
I'm probably not suitable to be the sole reviewer on NC tickets.
Most of my experience with the NC is watching you guys play with it in the interviews :D

If it is aesthetic/minor changes like this PR include @kmurica as well.
If it is digging into the bowels then include both @kmurica and @matthew-d-jones too.

That way we can all learn more and, hopefully, over the next few months we will build up enough NC knowledge that we won't need @matthew-d-jones T.T

**Comment by kmurica** [comment]
Looks nice! One general thing though.
The without text button layout looks like:
image
The with text buttons is:
image
As I have not used the tool much yet, would it be worthwhile trying to get all the buttons in the button panel visible without the dropdown list? That would probably require to enlarge the button panel to fit the labels . That might end up looking a bit ugly...

**Comment by ebadkamil** [comment]
users can expand the left panel using the splitter and then they all fit in.

**Comment by matthew-d-jones** [comment]
I'm not sure if the "zoom component" button does anything currently, if not you could remove it completely for now. That would help a little with the issue Kenan pointed out.

**Comment by ebadkamil** [comment]
if you select a component on the left panel and click on "zoom component" then it actually zooms in to the component. Although one can just use the scroll button for that.

**Comment by matthew-d-jones** [comment]
Oh great, for some reason I thought that wasn't working.

**Comment by ebadkamil** [comment]
I have renamed the actions rather than stretching the panels on triggering the show button labels. This way they all fit in easily,

**Review by kmurica — APPROVED** [review]
LGTM.

**Pull request merged**
