### PR TITLE
Ecdc 2395 fix mypy errors

### LINKED ISSUE #712: Mypy -> Found 290 errors in 61 files
One of the interviewees ran mypy against the code and it came back with  a number of errors. 
Theses should be investigated to see if they are actual errors and, if so, fixed.

### PR DESCRIPTION
**Pull request by kmurica**
### Issue

Closes #712

### Description of work

Major refactoring of nexus constructor code base to comply with mypy 0.812.

### Acceptance Criteria 

Changes made to fix mypy errors as well as unit test errors. I also added a pre-commit hook for mypy.
The reviewer should test to run nexus_constructor and see that there are no obvious errors introduced.
Although I think they should be caught by the unit tests anyway.
Check that the pre-commit work as intended by testing locally if it catches type errors (don't push anything :) ).

### UI tests

There haven't been any updates on the GUI side. The updates in this PR are on the backend side only.

### Nominate for Group Code Review

- Ebad and Ümit

### CODE REVIEW

**Comment by kmurica** [comment]
@ebadkamil and @umithardal Finally ready for review! We might need to have a short 30 minutes meeting prior to your review just to go through what I have done (just a general overview).

**Comment by kmurica** [comment]
@umithardal @ebadkamil I think I've managed to fix the JenkinsFile. Ready for review. 🖌️

**Comment by umithardal** [comment]
@kmurica I do not see Mypy in requirements but it is now in hooks. May be we should consider to add it to dev-requirements as well.

**Comment by kmurica** [comment]
> @kmurica I do not see Mypy in requirements but it is now in hooks. May be we should consider to add it to dev-requirements as well.

It is added now in the requirements-dev.txt

**Review by umithardal — APPROVED** [review]

**Comment by ebadkamil** [comment]
There is no issue with the application after these changes. It works all good. LGTM

**Review by ebadkamil — APPROVED** [review]

**Pull request merged**
